#from DSCI310 course notes

services:
  analysis-env: # name of the service we are creating
    image: eao939/dsci310-group16-docker:latest
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/project
    environment:
      PASSWORD: group16